import { sql } from '@payloadcms/db-postgres'
import type { MigrateUpArgs, MigrateDownArgs } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_provider_users_role" AS ENUM('super_admin', 'platform_admin', 'provider_manager', 'provider_staff');
  CREATE TYPE "public"."enum_providers_provider_type" AS ENUM('ngo_nonprofit', 'public_community', 'mental_health_counselling', 'university_student', 'helpline_immediate_support');
  CREATE TYPE "public"."enum_services_topics" AS ENUM('social_connection', 'emotional_wellbeing', 'family_relationships', 'work_unemployment', 'financial_basic_needs', 'housing_living', 'personal_safety', 'education_student', 'other_unsure');
  CREATE TYPE "public"."enum_services_coverage" AS ENUM('nicosia', 'limassol', 'larnaca', 'paphos', 'famagusta', 'anywhere_cyprus', 'online');
  CREATE TYPE "public"."enum_services_languages" AS ENUM('el', 'en');
  CREATE TYPE "public"."enum_services_delivery_modes" AS ENUM('online', 'in_person', 'phone');
  CREATE TYPE "public"."enum_contact_requests_contact_type" AS ENUM('email', 'phone');
  CREATE TYPE "public"."enum_contact_requests_status" AS ENUM('new', 'assigned', 'contact_attempted', 'contacted', 'accepted', 'closed', 'unable_to_reach', 'referred_elsewhere', 'user_declined');
  CREATE TYPE "public"."enum_provider_audit_events_event_type" AS ENUM('request_viewed', 'request_assigned', 'status_changed');
  CREATE TABLE "provider_organisations" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"name" varchar NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  CREATE TABLE "provider_users_sessions" ("_order" integer NOT NULL,"_parent_id" integer NOT NULL,"id" varchar PRIMARY KEY NOT NULL,"created_at" timestamp(3) with time zone,"expires_at" timestamp(3) with time zone NOT NULL);
  CREATE TABLE "provider_users" ("id" serial PRIMARY KEY NOT NULL,"role" "enum_provider_users_role" NOT NULL,"organisation_id" integer,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"email" varchar NOT NULL,"reset_password_token" varchar,"reset_password_expiration" timestamp(3) with time zone,"salt" varchar,"hash" varchar,"reset_password_requested_at" timestamp(3) with time zone,"login_attempts" numeric DEFAULT 0,"lock_until" timestamp(3) with time zone);
  CREATE TABLE "providers" ("id" serial PRIMARY KEY NOT NULL,"organisation_id" integer,"name" varchar NOT NULL,"provider_type" "enum_providers_provider_type" NOT NULL,"information_source" varchar NOT NULL,"information_checked_at" timestamp(3) with time zone NOT NULL,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "services_topics" ("order" integer NOT NULL,"parent_id" integer NOT NULL,"value" "enum_services_topics","id" serial PRIMARY KEY NOT NULL);
  CREATE TABLE "services_coverage" ("order" integer NOT NULL,"parent_id" integer NOT NULL,"value" "enum_services_coverage","id" serial PRIMARY KEY NOT NULL);
  CREATE TABLE "services_languages" ("order" integer NOT NULL,"parent_id" integer NOT NULL,"value" "enum_services_languages","id" serial PRIMARY KEY NOT NULL);
  CREATE TABLE "services_delivery_modes" ("order" integer NOT NULL,"parent_id" integer NOT NULL,"value" "enum_services_delivery_modes","id" serial PRIMARY KEY NOT NULL);
  CREATE TABLE "services" ("id" serial PRIMARY KEY NOT NULL,"provider_id" integer NOT NULL,"name" varchar NOT NULL,"availability" varchar,"immediate_support_capable" boolean DEFAULT false NOT NULL,"integrated" boolean DEFAULT false NOT NULL,"information_source" varchar NOT NULL,"information_checked_at" timestamp(3) with time zone NOT NULL,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "services_texts" ("id" serial PRIMARY KEY NOT NULL,"order" integer NOT NULL,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"text" varchar);
  CREATE TABLE "ephemeral_sessions" ("id" serial PRIMARY KEY NOT NULL,"session_id" varchar NOT NULL,"stage" varchar NOT NULL,"primary_support_topic" varchar,"service_area" varchar,"temporary_free_text" varchar,"safety_routing_state" varchar,"expires_at" timestamp(3) with time zone NOT NULL,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "ephemeral_sessions_texts" ("id" serial PRIMARY KEY NOT NULL,"order" integer NOT NULL,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"text" varchar);
  CREATE TABLE "anonymous_analytics_events" ("id" serial PRIMARY KEY NOT NULL,"primary_support_topic" varchar,"service_area" varchar,"interaction_outcome" varchar NOT NULL,"services_shown_count" numeric NOT NULL,"self_service_selected" boolean DEFAULT false NOT NULL,"assisted_contact_selected" boolean DEFAULT false NOT NULL,"no_match" boolean DEFAULT false NOT NULL,"taxonomy_version" varchar NOT NULL,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "anonymous_analytics_events_texts" ("id" serial PRIMARY KEY NOT NULL,"order" integer NOT NULL,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"text" varchar);
  CREATE TABLE "contact_requests" ("id" serial PRIMARY KEY NOT NULL,"provider_organisation_id" integer NOT NULL,"service_id" integer NOT NULL,"preferred_name" varchar,"contact_type" "enum_contact_requests_contact_type" NOT NULL,"contact_detail" varchar NOT NULL,"primary_support_topic" varchar NOT NULL,"service_area" varchar,"structured_support_summary" varchar NOT NULL,"optional_note" varchar,"status" "enum_contact_requests_status" DEFAULT 'new' NOT NULL,"assigned_provider_user_id" integer,"closed_at" timestamp(3) with time zone,"management_token_hash" varchar NOT NULL,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "contact_requests_texts" ("id" serial PRIMARY KEY NOT NULL,"order" integer NOT NULL,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"text" varchar);
  CREATE TABLE "consent_records" ("id" serial PRIMARY KEY NOT NULL,"request_id" integer NOT NULL,"consent_version" varchar NOT NULL,"recipient_provider_organisation_id" integer NOT NULL,"optional_note_authorised" boolean DEFAULT false NOT NULL,"consented_at" timestamp(3) with time zone NOT NULL,"withdrawn_at" timestamp(3) with time zone,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "consent_records_texts" ("id" serial PRIMARY KEY NOT NULL,"order" integer NOT NULL,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"text" varchar);
  CREATE TABLE "provider_audit_events" ("id" serial PRIMARY KEY NOT NULL,"actor_user_id" varchar NOT NULL,"organisation_id" varchar,"request_id" varchar NOT NULL,"event_type" "enum_provider_audit_events_event_type" NOT NULL,"occurred_at" timestamp(3) with time zone NOT NULL,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "payload_kv" ("id" serial PRIMARY KEY NOT NULL,"key" varchar NOT NULL,"data" jsonb NOT NULL);
  CREATE TABLE "payload_locked_documents" ("id" serial PRIMARY KEY NOT NULL,"global_slug" varchar,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "payload_locked_documents_rels" ("id" serial PRIMARY KEY NOT NULL,"order" integer,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"provider_organisations_id" integer,"provider_users_id" integer,"providers_id" integer,"services_id" integer,"ephemeral_sessions_id" integer,"anonymous_analytics_events_id" integer,"contact_requests_id" integer,"consent_records_id" integer,"provider_audit_events_id" integer);
  CREATE TABLE "payload_preferences" ("id" serial PRIMARY KEY NOT NULL,"key" varchar,"value" jsonb,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  CREATE TABLE "payload_preferences_rels" ("id" serial PRIMARY KEY NOT NULL,"order" integer,"parent_id" integer NOT NULL,"path" varchar NOT NULL,"provider_users_id" integer);
  CREATE TABLE "payload_migrations" ("id" serial PRIMARY KEY NOT NULL,"name" varchar,"batch" numeric,"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL);
  ALTER TABLE "provider_users_sessions" ADD CONSTRAINT "provider_users_sessions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."provider_users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "provider_users" ADD CONSTRAINT "provider_users_organisation_id_provider_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."provider_organisations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "providers" ADD CONSTRAINT "providers_organisation_id_provider_organisations_id_fk" FOREIGN KEY ("organisation_id") REFERENCES "public"."provider_organisations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "services_topics" ADD CONSTRAINT "services_topics_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "services_coverage" ADD CONSTRAINT "services_coverage_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "services_languages" ADD CONSTRAINT "services_languages_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "services_delivery_modes" ADD CONSTRAINT "services_delivery_modes_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "services" ADD CONSTRAINT "services_provider_id_providers_id_fk" FOREIGN KEY ("provider_id") REFERENCES "public"."providers"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "services_texts" ADD CONSTRAINT "services_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "ephemeral_sessions_texts" ADD CONSTRAINT "ephemeral_sessions_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."ephemeral_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "anonymous_analytics_events_texts" ADD CONSTRAINT "anonymous_analytics_events_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."anonymous_analytics_events"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "contact_requests" ADD CONSTRAINT "contact_requests_provider_organisation_id_provider_organisations_id_fk" FOREIGN KEY ("provider_organisation_id") REFERENCES "public"."provider_organisations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "contact_requests" ADD CONSTRAINT "contact_requests_service_id_services_id_fk" FOREIGN KEY ("service_id") REFERENCES "public"."services"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "contact_requests" ADD CONSTRAINT "contact_requests_assigned_provider_user_id_provider_users_id_fk" FOREIGN KEY ("assigned_provider_user_id") REFERENCES "public"."provider_users"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "contact_requests_texts" ADD CONSTRAINT "contact_requests_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."contact_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_request_id_contact_requests_id_fk" FOREIGN KEY ("request_id") REFERENCES "public"."contact_requests"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "consent_records" ADD CONSTRAINT "consent_records_recipient_provider_organisation_id_provider_organisations_id_fk" FOREIGN KEY ("recipient_provider_organisation_id") REFERENCES "public"."provider_organisations"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "consent_records_texts" ADD CONSTRAINT "consent_records_texts_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."consent_records"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_locked_documents"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_provider_organisations_fk" FOREIGN KEY ("provider_organisations_id") REFERENCES "public"."provider_organisations"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_provider_users_fk" FOREIGN KEY ("provider_users_id") REFERENCES "public"."provider_users"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_providers_fk" FOREIGN KEY ("providers_id") REFERENCES "public"."providers"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_ephemeral_sessions_fk" FOREIGN KEY ("ephemeral_sessions_id") REFERENCES "public"."ephemeral_sessions"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_anonymous_analytics_events_fk" FOREIGN KEY ("anonymous_analytics_events_id") REFERENCES "public"."anonymous_analytics_events"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_contact_requests_fk" FOREIGN KEY ("contact_requests_id") REFERENCES "public"."contact_requests"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_consent_records_fk" FOREIGN KEY ("consent_records_id") REFERENCES "public"."consent_records"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_provider_audit_events_fk" FOREIGN KEY ("provider_audit_events_id") REFERENCES "public"."provider_audit_events"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_preferences"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_provider_users_fk" FOREIGN KEY ("provider_users_id") REFERENCES "public"."provider_users"("id") ON DELETE cascade ON UPDATE no action;
  CREATE UNIQUE INDEX "provider_organisations_name_idx" ON "provider_organisations" USING btree ("name");
  CREATE INDEX "provider_organisations_updated_at_idx" ON "provider_organisations" USING btree ("updated_at"); CREATE INDEX "provider_organisations_created_at_idx" ON "provider_organisations" USING btree ("created_at");
  CREATE INDEX "provider_users_sessions_order_idx" ON "provider_users_sessions" USING btree ("_order"); CREATE INDEX "provider_users_sessions_parent_id_idx" ON "provider_users_sessions" USING btree ("_parent_id"); CREATE INDEX "provider_users_organisation_idx" ON "provider_users" USING btree ("organisation_id"); CREATE INDEX "provider_users_updated_at_idx" ON "provider_users" USING btree ("updated_at"); CREATE INDEX "provider_users_created_at_idx" ON "provider_users" USING btree ("created_at"); CREATE UNIQUE INDEX "provider_users_email_idx" ON "provider_users" USING btree ("email");
  CREATE INDEX "providers_organisation_idx" ON "providers" USING btree ("organisation_id"); CREATE INDEX "providers_updated_at_idx" ON "providers" USING btree ("updated_at"); CREATE INDEX "providers_created_at_idx" ON "providers" USING btree ("created_at");
  CREATE INDEX "services_topics_order_idx" ON "services_topics" USING btree ("order"); CREATE INDEX "services_topics_parent_idx" ON "services_topics" USING btree ("parent_id"); CREATE INDEX "services_coverage_order_idx" ON "services_coverage" USING btree ("order"); CREATE INDEX "services_coverage_parent_idx" ON "services_coverage" USING btree ("parent_id"); CREATE INDEX "services_languages_order_idx" ON "services_languages" USING btree ("order"); CREATE INDEX "services_languages_parent_idx" ON "services_languages" USING btree ("parent_id"); CREATE INDEX "services_delivery_modes_order_idx" ON "services_delivery_modes" USING btree ("order"); CREATE INDEX "services_delivery_modes_parent_idx" ON "services_delivery_modes" USING btree ("parent_id"); CREATE INDEX "services_provider_idx" ON "services" USING btree ("provider_id"); CREATE INDEX "services_updated_at_idx" ON "services" USING btree ("updated_at"); CREATE INDEX "services_created_at_idx" ON "services" USING btree ("created_at"); CREATE INDEX "services_texts_order_parent" ON "services_texts" USING btree ("order","parent_id");
  CREATE UNIQUE INDEX "ephemeral_sessions_session_id_idx" ON "ephemeral_sessions" USING btree ("session_id"); CREATE INDEX "ephemeral_sessions_expires_at_idx" ON "ephemeral_sessions" USING btree ("expires_at"); CREATE INDEX "ephemeral_sessions_updated_at_idx" ON "ephemeral_sessions" USING btree ("updated_at"); CREATE INDEX "ephemeral_sessions_created_at_idx" ON "ephemeral_sessions" USING btree ("created_at"); CREATE INDEX "ephemeral_sessions_texts_order_parent" ON "ephemeral_sessions_texts" USING btree ("order","parent_id");
  CREATE INDEX "anonymous_analytics_events_updated_at_idx" ON "anonymous_analytics_events" USING btree ("updated_at"); CREATE INDEX "anonymous_analytics_events_created_at_idx" ON "anonymous_analytics_events" USING btree ("created_at"); CREATE INDEX "anonymous_analytics_events_texts_order_parent" ON "anonymous_analytics_events_texts" USING btree ("order","parent_id");
  CREATE INDEX "contact_requests_provider_organisation_idx" ON "contact_requests" USING btree ("provider_organisation_id"); CREATE INDEX "contact_requests_service_idx" ON "contact_requests" USING btree ("service_id"); CREATE INDEX "contact_requests_assigned_provider_user_idx" ON "contact_requests" USING btree ("assigned_provider_user_id"); CREATE INDEX "contact_requests_updated_at_idx" ON "contact_requests" USING btree ("updated_at"); CREATE INDEX "contact_requests_created_at_idx" ON "contact_requests" USING btree ("created_at"); CREATE INDEX "contact_requests_texts_order_parent" ON "contact_requests_texts" USING btree ("order","parent_id");
  CREATE INDEX "consent_records_request_idx" ON "consent_records" USING btree ("request_id"); CREATE INDEX "consent_records_recipient_provider_organisation_idx" ON "consent_records" USING btree ("recipient_provider_organisation_id"); CREATE INDEX "consent_records_updated_at_idx" ON "consent_records" USING btree ("updated_at"); CREATE INDEX "consent_records_created_at_idx" ON "consent_records" USING btree ("created_at"); CREATE INDEX "consent_records_texts_order_parent" ON "consent_records_texts" USING btree ("order","parent_id");
  CREATE INDEX "provider_audit_events_request_id_idx" ON "provider_audit_events" USING btree ("request_id"); CREATE INDEX "provider_audit_events_updated_at_idx" ON "provider_audit_events" USING btree ("updated_at"); CREATE INDEX "provider_audit_events_created_at_idx" ON "provider_audit_events" USING btree ("created_at");
  CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload_kv" USING btree ("key"); CREATE INDEX "payload_locked_documents_global_slug_idx" ON "payload_locked_documents" USING btree ("global_slug"); CREATE INDEX "payload_locked_documents_updated_at_idx" ON "payload_locked_documents" USING btree ("updated_at"); CREATE INDEX "payload_locked_documents_created_at_idx" ON "payload_locked_documents" USING btree ("created_at");
  CREATE INDEX "payload_locked_documents_rels_order_idx" ON "payload_locked_documents_rels" USING btree ("order"); CREATE INDEX "payload_locked_documents_rels_parent_idx" ON "payload_locked_documents_rels" USING btree ("parent_id"); CREATE INDEX "payload_locked_documents_rels_path_idx" ON "payload_locked_documents_rels" USING btree ("path"); CREATE INDEX "payload_locked_documents_rels_provider_organisations_id_idx" ON "payload_locked_documents_rels" USING btree ("provider_organisations_id"); CREATE INDEX "payload_locked_documents_rels_provider_users_id_idx" ON "payload_locked_documents_rels" USING btree ("provider_users_id"); CREATE INDEX "payload_locked_documents_rels_providers_id_idx" ON "payload_locked_documents_rels" USING btree ("providers_id"); CREATE INDEX "payload_locked_documents_rels_services_id_idx" ON "payload_locked_documents_rels" USING btree ("services_id"); CREATE INDEX "payload_locked_documents_rels_ephemeral_sessions_id_idx" ON "payload_locked_documents_rels" USING btree ("ephemeral_sessions_id"); CREATE INDEX "payload_locked_documents_rels_anonymous_analytics_events_idx" ON "payload_locked_documents_rels" USING btree ("anonymous_analytics_events_id"); CREATE INDEX "payload_locked_documents_rels_contact_requests_id_idx" ON "payload_locked_documents_rels" USING btree ("contact_requests_id"); CREATE INDEX "payload_locked_documents_rels_consent_records_id_idx" ON "payload_locked_documents_rels" USING btree ("consent_records_id"); CREATE INDEX "payload_locked_documents_rels_provider_audit_events_id_idx" ON "payload_locked_documents_rels" USING btree ("provider_audit_events_id");
  CREATE INDEX "payload_preferences_key_idx" ON "payload_preferences" USING btree ("key"); CREATE INDEX "payload_preferences_updated_at_idx" ON "payload_preferences" USING btree ("updated_at"); CREATE INDEX "payload_preferences_created_at_idx" ON "payload_preferences" USING btree ("created_at"); CREATE INDEX "payload_preferences_rels_order_idx" ON "payload_preferences_rels" USING btree ("order"); CREATE INDEX "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" USING btree ("parent_id"); CREATE INDEX "payload_preferences_rels_path_idx" ON "payload_preferences_rels" USING btree ("path"); CREATE INDEX "payload_preferences_rels_provider_users_id_idx" ON "payload_preferences_rels" USING btree ("provider_users_id"); CREATE INDEX "payload_migrations_updated_at_idx" ON "payload_migrations" USING btree ("updated_at"); CREATE INDEX "payload_migrations_created_at_idx" ON "payload_migrations" USING btree ("created_at");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "provider_organisations" CASCADE; DROP TABLE "provider_users_sessions" CASCADE; DROP TABLE "provider_users" CASCADE; DROP TABLE "providers" CASCADE; DROP TABLE "services_topics" CASCADE; DROP TABLE "services_coverage" CASCADE; DROP TABLE "services_languages" CASCADE; DROP TABLE "services_delivery_modes" CASCADE; DROP TABLE "services" CASCADE; DROP TABLE "services_texts" CASCADE; DROP TABLE "ephemeral_sessions" CASCADE; DROP TABLE "ephemeral_sessions_texts" CASCADE; DROP TABLE "anonymous_analytics_events" CASCADE; DROP TABLE "anonymous_analytics_events_texts" CASCADE; DROP TABLE "contact_requests" CASCADE; DROP TABLE "contact_requests_texts" CASCADE; DROP TABLE "consent_records" CASCADE; DROP TABLE "consent_records_texts" CASCADE; DROP TABLE "provider_audit_events" CASCADE; DROP TABLE "payload_kv" CASCADE; DROP TABLE "payload_locked_documents" CASCADE; DROP TABLE "payload_locked_documents_rels" CASCADE; DROP TABLE "payload_preferences" CASCADE; DROP TABLE "payload_preferences_rels" CASCADE; DROP TABLE "payload_migrations" CASCADE;
  DROP TYPE "public"."enum_provider_users_role"; DROP TYPE "public"."enum_providers_provider_type"; DROP TYPE "public"."enum_services_topics"; DROP TYPE "public"."enum_services_coverage"; DROP TYPE "public"."enum_services_languages"; DROP TYPE "public"."enum_services_delivery_modes"; DROP TYPE "public"."enum_contact_requests_contact_type"; DROP TYPE "public"."enum_contact_requests_status"; DROP TYPE "public"."enum_provider_audit_events_event_type";`)
}
